version: '3.8'

services:
  dev_db:
    image: mysql:latest
    container_name: dev_db
    # 開發測試不用
    # volumes:
    #   - ./mysql:/var/lib/mysql
    restart: always
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: project
      TZ: Asia/Taipei
      # ports:
      # - "3306:3306"                  # 沒有要expose 留著方便對照

  dev_backend_server:
    # image: lipheris/project-server:latest
    build:
      dockerfile: Dockerfile
    container_name: dev_backend_server
    restart: always
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dev_db:3306/project?createDatabaseIfNotExist=true&serverTimezone=Asia/Taipei&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd # MySQL密碼
      PIC_STORAGE_PATH: pictures #開發測試用
    volumes:
      - ./src/main/resources/static/pictures:/app/pictures
    depends_on:
      - dev_db
      # ports:
      # - "8080:8080"                # 沒有要expose 留著方便對照
      
  dev_frontend_server:
    image: nginx:alpine
    container_name: dev_frontend_server
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf
      # - ./html:/usr/share/nginx/html
      - ./src/main/resources/static/html:/usr/share/nginx/html
      - ./src/main/resources/static/pictures:/usr/share/nginx/html/pictures
    depends_on:
      - dev_backend_server
    ports:
      - "81:80"
