version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: project
      TZ: Asia/Taipei
      # ports:
      # - "3306:3306"                  # 沒有要expose 留著方便對照

  backend_server:
    image: lipheris/project-server:latest
    container_name: backend_server
    restart: always
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/project?createDatabaseIfNotExist=true&serverTimezone=Asia/Taipei&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd # MySQL密碼
    depends_on:
      - db
      # ports:
      # - "8080:8080"                # 沒有要expose 留著方便對照
      
  frontend_server:
    image: nginx:alpine
    container_name: frontend_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - backend_server
    ports:
      - "80:80"
