-- database
create database if not exists project;
use project;

-- picture
create table if not exists project.picture (
    pic_id int auto_increment primary key not null,
    pic_created_at timestamp default current_timestamp,
    pic_loc varchar(50),
    x_1 double,
    y_1 double,
    x_2 double,
    y_2 double,
	x_3 double,
    y_3 double,
    x_4 double,
    y_4 double,
    x_5 double,
    y_5 double,
    x_6 double,
    y_6 double,
	x_7 double,
    y_7 double,
    x_8 double,
    y_8 double,
    x_9 double,
    y_9 double,
    x_10 double,
    y_10 double,
	x_11 double,
    y_11 double,
    x_12 double,
    y_12 double,
    x_13 double,
    y_13 double,
    x_14 double,
    y_14 double,
	x_15 double,
    y_15 double,
    x_16 double,
    y_16 double,
    x_17 double,
    y_17 double,
    index idx_pic_loc (pic_loc)
);
